import { injectJsError } from "./lib/jsError";
import injectXHR from "./lib/xhr";
import blankscreen from "./lib/blankscreen";
import timing from "./lib/timing";
import pv from "./lib/pv";
injectJsError();
injectXHR();
blankscreen();
timing();
pv();
